[package]
name = "motoko-rts-tests"
version = "0.1.0"
authors = ["dfinity <sdk@dfinity.org"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
libc = { version = "0.2.81", default_features = false }
motoko-rts = { path = "../motoko-rts/native" }
proptest = { version = "1.0.0", default-features = false, features = ["std"] }

# This is not a dep of tests but we have it here as we use this file to vendor
# dependencies or motoko-rts
wee_alloc = "0.4.5"
