[package]
name = "motoko-rts"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]
path = "../src/lib.rs"

[dependencies]
libc = { version = "0.2.73", default_features = false }
utf8-width = "0.1.4"

[dependencies.compiler_builtins]
version = "0.1.32"
features = ["mangled-names"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
