name: Update niv dependencies (weekly)
on:
  # Manual override, one can start the workflow by running:
  # curl -H "Accept: application/vnd.github.everest-preview+json" \
  #  -H "Authorization: token <your-token-here>" \
  #  --request POST \
  #  --data '{"event_type": "niv-updater-nudge", "client_payload": {}}' \
  #  https://api.github.com/repos/dfinity-lab/motoko/dispatches
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
  repository_dispatch:
    types: niv-updater-nudge
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every monday
    - cron:  '0 0 * * 1'
jobs:
  niv-updater:
    name: 'Check for updates'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@dbe84dffd27c7b5079dd748ce61a3e9797a68cf8
        with:
          # might be too noisy
          whitelist: 'dfinity,ic-ref,musl-wasi,common,niv'
          labels: |
            automerge-squash
          keep_updating: true
        env:
          GITHUB_TOKEN: ${{ secrets.NIV_UPDATER_TOKEN }}
